### ISSUE TITLE
Predefined speed dials for internal pages

### ISSUE THREAD

**Issue by luetage** [An-dz/VSDGenerator#1]
Just a suggestion. I guess it would be an option to save predefined speed dials to the extension, which can’t be generated, such as the chrome web store and Vivaldi’s internal pages. Maybe existing Vivaldi speed dials too, like the one for Vivaldi Community, Web Mail, Bug Report and Forum.

**Comment by An-dz** [comment]
Unfortunately, this is impossible.

The way this extension works is by injecting a script on the page. It's always running even when not generating a SD, but when not on a SD generation it simply aborts before executing anything else.

And since it runs on the page it can't change the SD generation of internal pages as those are protected from extensions, extensions can't run on them.

Things I've been trying to put on this extensions that I know there's a chance of working is allowing the user to set a CSS query string that allows getting a specific part of the page, like an HD image, to display as the SD. This would allow sites like video sharing, game mods and movie databases to show the image of the content.

**Comment by luetage** [comment]
Ahh, no problem. I obviously lack insight. I imagined you could check for URL and intercept, but it’s fine as is.
